package com.zuul.bootdemo.dao;

import com.zuul.bootdemo.domain.entity.CanalTestDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Component;
import org.springframework.stereotype.Repository;

@Component
public interface CanalTestDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    int insert(CanalTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    int insertSelective(CanalTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    CanalTestDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CanalTestDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table canal_test
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CanalTestDO record);
}