package com.zuul.bootdemo.domain.entity;

public class CanalTestDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canal_test.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column canal_test.c_name
     *
     * @mbg.generated
     */
    private String cName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canal_test.id
     *
     * @return the value of canal_test.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canal_test.id
     *
     * @param id the value for canal_test.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column canal_test.c_name
     *
     * @return the value of canal_test.c_name
     *
     * @mbg.generated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column canal_test.c_name
     *
     * @param cName the value for canal_test.c_name
     *
     * @mbg.generated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }
}