server:
  port: 9000

endpoints:
  shutdown:
    sensitive: false
    enabled: true
## curl -X POST http://127.0.0.1:9000/shutdown  服务下线命令


eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/